"""Adds the Balances Table

Revision ID: 3331ef8a5cf2
Revises: 2ebceb2f1b28
Create Date: 2024-09-17 19:18:13.692428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3331ef8a5cf2'
down_revision: Union[str, None] = '2ebceb2f1b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('airtime_balance', sa.Float(), nullable=True),
    sa.Column('bundles_balance', sa.Float(), nullable=True),
    sa.Column('mpesa_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balances')
    # ### end Alembic commands ###
